-- AI moderation explainer — fan-facing message column
-- Idempotent.

alter table public.community_posts
  add column if not exists moderation_user_message text;

comment on column public.community_posts.moderation_user_message is
  'Fan-facing 1-sentence explanation when moderation_status=auto_hide. Generated by Claude Haiku via /api/cron/moderation-explain. Rendered as a chip below the post body, visible only to the author. NULL when status != auto_hide or backfill hasn''t run yet.';
